using System;
using System.IO;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using Utitshala.Models;
using Utitshala.Controllers;

namespace Utitshala.Services
{
    /// <summary>
    /// Handles file I/O.
    /// </summary>
    public class FileSystemManager
    {
        public bool SaveFile(object file, AssignmentType type, string userId, int assignmentId)
        {
            switch (type)
            {
                case AssignmentType.Image:
                    Image image = (Image)file;
                    string fileName = GUIDGenerator() + ".jpg";
                    // Save the file to the user's folder
                    try
                    {
                        // Check to see if a student folder exists with this ID
                        string directory = AppDomain.CurrentDomain.BaseDirectory + @"StudentAssignments\" + userId;
                        if (!Directory.Exists(directory))
                        {
                            Directory.CreateDirectory(directory);
                        }
                        // Save to the folder
                        string imageDirectory = directory + @"\" + fileName;
                        image.Save(imageDirectory, System.Drawing.Imaging.ImageFormat.Jpeg);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.StackTrace);
                    }
                    // Create a database element recording the GUID and assignment
                    DatabaseController.SaveStudentAssignment(userId, fileName, 0, assignmentId);
                    break;
            }
            return true;
        }

        /// <summary>
        /// Generates a unique GUID for unique file names.
        /// </summary>
        /// <param name="length">The string length of the GUID.</param>
        /// <returns>The GUID generated by this method.</returns>
        public string GUIDGenerator(int length = 16)
        {
            var SHA = SHA256.Create();
            byte[] toHash = SHA.ComputeHash(Encoding.UTF8.GetBytes(DateTime.Now.ToString()));
            string hash = BitConverter.ToString(toHash).Replace("-", String.Empty);
            hash = hash.Substring(0, length);
            return hash;
        }
    }
}